### ISSUE TITLE
Karabiner-Elements 13.3.0 kernal panic on M1 Big Sur

### ISSUE THREAD

**Issue by matsuda0707** [pqrs-org/Karabiner-Elements#2607] opened 2021-01-30 02:36 UTC
Today Karabiner-Elements 13.3.0 was released, but it cause Kernel panic after installation.
The installation itself completed successfully, but after every power on and restart, the kernal panic message appears but Karabiner-Elements itself is available for Key operation!
In the previous 13.1.0 caused restart after install, but 13.3.0 only cause kernal panic but usable.
A little improvement, but not fully compatible to M1 mac!

**Comment by tekezo** [comment] 2021-01-30 06:55
Karabiner-Elements is no longer related to the kernel, so the cause is either macOS or some other third vendor application.

Please file an issue to Apple BTS about kernel panic.

**Comment by matsuda0707** [comment] 2021-01-30 07:47
I installed Big Sur 11.1 to external device which is pure M1 native and no application.
After switch to the external device, and installed Karabiner-Elements 13.3.0 and a few setting for Japanese keyboard, and I restarted.
Then the attached message appeared after restart.
![screenshot 2021-01-30 16 20 52](https://user-images.githubusercontent.com/22485788/106350727-79e0b080-631a-11eb-9fef-9912a41d6f2f.png)

The detaile information is as follows;
![screenshot 2021-01-30 16 21 05](https://user-images.githubusercontent.com/22485788/106350735-8fee7100-631a-11eb-910c-1fb93592e7ae.png)

**Comment by tekezo** [comment] 2021-01-30 12:18
Thank you for your confirmation!

In that situation, the kernel panic is most likely caused by a bug in the macOS DriverKit or HID driver.
There is no workaround on Karabiner-Elements, we need to work on getting macOS fixed by reporting the issue to Apple.

**Comment by henkers** [comment] 2021-01-30 15:07
I'm sorry to say I'm also still experiencing this issue with Karabiner-Elements 13.3.0 on a Macbook Air with the M1 chip. 

I experienced the same kernel panic error with previous versions of Karabiner-Elements and I was hoping this will fix the problem. 

If I uninstall Karabiner-Elements I don't get the kernel panic error report after a restart. After I re-install it, I get the error again. 

I hear you @tekezo, that it might be an Apple issue, and that we need to report it to Apple. I'm not sure how to do that. 

Thank you.

**Comment by matsuda0707** [comment] 2021-01-30 15:39
For the developers, I would like to confirm you that you fully tested  on real M1 mac and released the Karabiner-Elements.
This error might be easily  found by just installing and restarting the system.
You should not say "Both Intel-based Macs and Apple Silicon Macs are supported" on  Karabiner-Elements page.
I would like to hear your answer why this error was not found before release.

**Comment by hackftz** [comment] 2021-01-30 17:09
This version is getting worse and worse!

**Comment by lucifron1994** [comment] 2021-01-31 02:55
（using m1 Mac mini）I was update to 13.3.0 yesterday and rebooted and slept several times, I haven't encountered any of the crashes that occurred 100% of the time before.（By the way, I have previously uninstalled the software, yesterday was a new installation）

**Comment by samplue** [comment] 2021-01-31 19:21
I have experienced exactly the same issues with a Mac mini M1 - kernel panics and crashes all the time. Installing the previous version 13.1.0 seems to work a little better, but still crashing from time time.

**Comment by yogendrasinghx** [comment] 2021-02-01 23:12
I'm also facing same problem with latest karabiner-Elements version on my new M1 mac mini. I can confirm after uninstalling karabiner-elements mac works just fine. and just after installing karabiner-elements and if i try to shutdown my it restarted with kernal panic message.

**Comment by nintendork07** [comment] 2021-02-04 22:43
really annoying issue, present on my m1 air as well. it can cause crashes and the error screen after rebooting keeps coming. i had to completely uninstall which sucks because one of the main reasons i got the air was to remap the F3 and F4 keys in karabiner to keyboard brightness controls which were replaced

**Comment by YuryRadchenko** [comment] 2021-02-05 11:41
I have panic error too. MacBook Pro M1 BigSur 11.2 (20D64). I removed the app :(

**Comment by alxmueller** [comment] 2021-02-07 08:08
Same problem here with Karabiner-Elements 13.3.0 after updating my 13" M1 MacBook Pro to macOS Big Sur 11.2.  System immediately reboots after shutdown and shows a crash message after login.  Problem disappeared after uninstalling Karabiner-Elements.

**Comment by scholarazwa** [comment] 2021-02-13 15:52
I can confirm the panic attack issue on M1 macs. Any chance this will be fixed soon? I really need Karabiner to work on my machine. Thank you.

**Comment by macwinnie** [comment] 2021-02-26 08:25
Already reported with https://github.com/pqrs-org/Karabiner-Elements/issues/2517

**Comment by KyleHKT** [comment] 2021-03-09 04:41
same problem in my mac mini
M1 Big Sur 11.2.2

**Comment by wpix** [comment] 2021-03-15 20:45
MacBook Pro (13-inch, M1, 2020)
macOS 11.2.3 (20D91)

kernel panic still occurs

**Comment by uhuznaa** [comment] 2021-03-15 23:00
Can we please escalate this a bit? Right now Karabiner just doesn't work on M1 Macs. I really want to have it working again, I really, really miss it.

**Comment by damianofranzo** [comment] 2021-03-18 21:44
Same problem here with version 13.3.0
M1 Big Sur 11.2.3

**Comment by cancng** [comment] 2021-03-20 21:18
same problem at Big Sur 11.2.3 (20D91)

**Comment by nealeyoung** [comment] 2021-03-24 19:14
I also have the same problem at 11.2.3 (20D91), mac mini M1, Karabiner elements 13.3.0

**Comment by tekezo** [comment] 2021-03-28 14:11
This issue was caused by an issue of macOS Big Sur kernel on Apple Silicon that is caused by using DriverKit.
Karabiner-Elements is using DriverKit and the usage invokes the kernel issue and causes kernel panic, and there was no practical workaround to avoid the issue.

However, this macOS problem has been fixed in macOS Big Sur 11.3 Beta!

There is no panics on M1 macs with the latest beta of macOS Big Sur.
https://beta.apple.com/sp/betaprogram/

**Comment by rstcruzo** [comment] 2021-04-27 02:13
This is still happening on Big Sur 11.3 stable version. When I try to enter sleep, sometimes it works sometimes it doesn’t. Had to uninstall Karabiner again.

**Closed** 2024-09-17 16:59 UTC
