### ISSUE TITLE
Mouse events interrupt keyboard in macOS Catalina.

### ISSUE THREAD

**Issue by topjung3** [pqrs-org/Karabiner-Elements#2304] opened 2020-05-29 09:52 UTC
I use a Windows keyboard with Ctrl Key for Command and Alt Key for Control. However, I want to use the switching application feature in mac (command+tab) Alt+tab, so I made a below complex_modification script.

After I update macOS Mojave to Catalina, Mouse events interrupt lazy options.

```
{
  "description": "Change shortcut switching applications as in Windows.",
  "manipulators": [
    {
      "type": "basic",
      "from": {
        "key_code": "left_shift",
        "modifiers": {
          "mandatory": [
            "left_control"
          ],
          "optional": [
            "caps_lock"
          ]
        }
      },
      "to": [
        {
          "key_code": "left_shift",
          "lazy": true,
          "modifiers": [
            "left_control"
          ]
        }
      ]
    },
    {
      "type": "basic",
      "from": {
        "key_code": "tab",
        "modifiers": {
          "mandatory": [
            "left_control"
          ],
          "optional": [
            "left_shift",
            "caps_lock"
          ]
        }
      },
      "to": [
        {
          "key_code": "tab",
          "modifiers": [
            "left_command"
          ]
        }
      ]
    },
    {
      "type": "basic",
      "from": {
        "key_code": "tab",
        "modifiers": {
          "mandatory": [
            "left_command"
          ],
          "optional": [
            "left_shift",
            "caps_lock"
          ]
        }
      },
      "to": [
        {
          "key_code": "tab",
          "modifiers": [
            "left_control"
          ]
        }
      ]
    },
    {
      "type": "basic",
      "from": {
        "key_code": "grave_accent_and_tilde",
        "modifiers": {
          "mandatory": [
            "left_control"
          ],
          "optional": [
            "left_shift",
            "caps_lock"
          ]
        }
      },
      "to": [
        {
          "key_code": "grave_accent_and_tilde",
          "modifiers": [
            "left_command"
          ]
        }
      ]
    },
    {
      "type": "basic",
      "from": {
        "key_code": "grave_accent_and_tilde",
        "modifiers": {
          "mandatory": [
            "left_control"
          ],
          "optional": [
            "left_shift",
            "caps_lock"
          ]
        }
      },
      "to": [
        {
          "key_code": "grave_accent_and_tilde",
          "modifiers": [
            "left_command"
          ]
        }
      ]
    }
  ]
}
```

In EventViewer, Number 6-8 events have been triggered When I move the mouse. Usually, in Mojave, not happened (6-8 events). These events make switching applications panel gone.
```
1 type:key_down        code:224        name:left_control    misc:flags: left_control 
2 type:key_up          code:224        name:left_control    misc:
3 type:key_down        code:227        name:left_command    misc:flags: left_command 
4 type:key_down        code:43         name:tab             misc:flags: left_command 
5 type:key_up          code:43         name:tab             misc:flags: left_command 
6 type:key_down        code:224        name:left_control    misc:flags: left_command,left_control 
7 type:key_up          code:227        name:left_command    misc:flags: left_control 
8 type:key_up          code:224        name:left_control    misc:
```

I disable other devices except for the keyboard, but this problem still happens.
![image](https://user-images.githubusercontent.com/2057348/83246612-5b4f7600-a1dd-11ea-91a7-1a88e3b6c27e.png)

Thanks.

**Comment by pieuvre** [comment] 2020-06-26 14:25
I've got the exact same issue : 

Simple modifications : left_gui -> left_control and left_control -> left_gui 
Complex modification : 
```
{
      "manipulators": [
        {
          "from": {
            "key_code": "grave_accent_and_tilde",
            "modifiers": {
              "mandatory": [
                "left_alt"
              ],
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "tab",
              "modifiers": [
                "left_gui"
              ]
            }
          ],
          "type": "basic"
        }
      ]
    }

```

While holding left_alt and any mouse movement generate the last two events : 

```
type:key_down        code:226        name:left_alt        misc:flags: left_alt 
type:key_up          code:226        name:left_alt        misc:
type:key_down        code:227        name:left_gui        misc:flags: left_gui 
type:key_down        code:43         name:tab             misc:flags: left_gui 
type:key_up          code:43         name:tab             misc:flags: left_gui 
type:key_down        code:226        name:left_alt        misc:flags: left_alt,left_gui 
type:key_up          code:227        name:left_gui        misc:flags: left_alt 

```

It seems somewhat related to #2313 because I can reproduce the behaviour by pressing any key while holding alt.

**Comment by nathang21** [comment] 2020-08-30 17:13
This is still an issue.

**Comment by pieuvre** [comment] 2020-08-30 20:11
Indeed

Kind regards,

Pierre Bouchard
0033 6957 05727

**Comment by marcomeyer** [comment] 2020-09-12 07:14
Same here. I'm on beta Version 12.10.4

**Comment by sdeneen** [comment] 2020-10-08 13:54
I'm also having this issue, on version 13.0.0.

![Screen Shot 2020-10-08 at 9 53 01 AM](https://user-images.githubusercontent.com/6738698/95468056-2356fd00-094c-11eb-8073-518aa6c3fe38.png)

**Comment by Sleepful** [comment] 2020-11-10 17:37
I'm experiencing this issue as well. Perhaps mouse events can be added as an optional modifier, that way if the mouse event happens then karabiner interprets it as part of the keybinding? I don't know.

**Comment by be9em0t** [comment] 2021-06-12 13:03
The issue persists.

**Comment by DanKaplanSES** [comment] 2021-07-28 22:20
On Big Sur. Still happens

**Comment by reed-coder** [comment] 2021-08-19 15:22
I am also having this issue.

**Comment by nopjia** [comment] 2022-05-31 18:22
This is still an issue. Monterey 12.3.1

Here is my json
```json
{
    "description": "swap command+tab and control+tab",
    "manipulators": [
        {
            "from": {
                "key_code": "tab",
                "modifiers": {
                    "mandatory": [
                        "command"
                    ],
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "tab",
                    "modifiers": [
                        "control"
                    ]
                }
            ],
            "type": "basic"
        },
        {
            "from": {
                "key_code": "tab",
                "modifiers": {
                    "mandatory": [
                        "control"
                    ],
                    "optional": [
                        "any"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "tab",
                    "modifiers": [
                        "command"
                    ]
                }
            ],
            "type": "basic"
        }
    ]
}
```

**Comment by franco-ruggeri** [comment] 2022-08-31 12:26
Hi, this is still an issue in macOS Monterey 12.5.1. As far as I can see, many people would benefit from a fix.

**Comment by iangreenleaf** [comment] 2024-04-02 20:15
There is more discussion about this issue in #2642 and #281. I'd recommend closing this issue and subscribing to those to make sure you get updates. A workaround that seems to work well can be found here: https://github.com/pqrs-org/Karabiner-Elements/issues/2642#issuecomment-1932890170

**Closed** 2024-08-30 15:40 UTC
Labels: bug, duplicate
