### ISSUE TITLE
Multiple, repeating modifier keys

### ISSUE THREAD

**Issue by paulcarbone** [pqrs-org/Karabiner-Elements#2759] opened 2021-07-07 01:33 UTC
I am in the process of setting up Karabiner to replace ControllerMate for an N52 Nostromo controller, which now shows up as the left-hand portion of a standard keyboard.
I have a number of complex modification rules, all of which are using "frontmost_application_if", and "device_if" to limit scope.  I have two rules that work on their own, but do not work when pressed together:

"from": { "key_code": "r" },"to": [  {"key_code": "left_shift", "repeat": true } ]
and
"from": { "key_code": "spacebar" }, "to": [  {"key_code": "left_alt" } ]

With 'R' held, I get 'shift', but once I also press 'spacebar', instead of getting 'alt', I get 'shift' and 'spacebar'
I also tried setting a variable with the shift rule, and had a second 'alt-shift' rule that triggers on 'spacebar' + the variable, but it won't fire, and it seems like it has something do to with a modifier being held on repeat.  
thanks,
Paul

**Comment by paulcarbone** [comment] 2021-11-21 17:49
Hi - thank you both, @MuhammedZakir & @clemsam 
Understood on not needing repeat, thank you. 
I think, however, that `lazy` isn't what I want, because "r"==>"Shift" and "space"==>"alt" need to work on their own (which they do). 
What ended up working was putting `"modifiers":{"optional":["shift"]}` on the space->alt rule and `"modifiers":{"optional":["option"]}` on the other rule.  Thanks for pointing me in that direction Muhammed!

**Comment by MuhammedZakir** [comment] 2021-11-21 18:07
You're welcome! :-)

If the problem is solved, please close this issue. :-)

**Closed** 2021-11-21 18:21 UTC
