### ISSUE TITLE
Karabiner missing Dictation and DnD Keys

### ISSUE THREAD

**Issue by DelusionalAI** [pqrs-org/Karabiner-Elements#2564] opened 2021-01-04 17:16 UTC
The new M1 Macs have a new Dictation/Siri key and Do not Disturb toggle key on F5 and F6 instead of the keyboard brightness adjust keys. When Karabiner is active the keys are remapped to the keyboard brightness keys, with no option to switch them to the correct new keys.

Is this something that can be added to Karabiner or is it a case of Mac doing their own thing instead of key codes that can be copied.

**Comment by MuhammedZakir** [comment] 2021-01-04 18:39
Dictionary and Spotlight was added to latest beta version. Unfortunately, no DND button atm. See https://github.com/pqrs-org/Karabiner-Elements/issues/2516#issuecomment-750303670.


Duplicate of #2516. Please close this issue.

**Closed** 2021-01-04 18:41 UTC
